// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Note: the Prisma CLI's schema engine only speaks `file:` for SQLite — it
// rejects `libsql://` with P1013. So migrations cannot run against Turso here.
// Apply schema changes to Turso out of band; see README / `prisma migrate diff`.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
